= Design of solution
:experimental:
:nofooter:
:source-highlighter: highlightjs
:sectnums:
:stem: latexmath
:toc:
:xrefstyle: short


[[object_design]]
== Object-oriented design
The class diagram for the program can be found below, with updated classes. Notice that the threads related structs were removed, given that declarative concurrency made them irrelevant to this version of the heat simulation. On the other hand, a new struct was added for distribution between processes: mpi_t. This register stores the process's rank or number, and the total amount of processes involved in the execution. It also contains wrapper functions to send and receive messages between processes. To adjust for distribution, separate procedures for master and worker processes were added to job.

[#class_diagram]
.UML class diagram for the program
image::omp_mpi_class_diagram.svg[align="center"]

[[concurrent_design]]
== Concurrent Design
The concurrent design for simulating heat transfer of plates remained the same, but implemented with Open MP, which will expand the static map by block approach implemented in the previous version: the combination of boolean flags that will indicate if the plate is equilibrated, the incrementation of iterations recorded and switching of matrices, and the barrier assuring threads start new states at the same time, are all summarized into omp declarations.

[#concurrent_static_design]
.Static map by blocks implemented
image::heat_simul_static_design.svg[align="center"]

[[distributed_design]]
== Distribution design

To implement a dynamic distribution of work between workers, the following design was thought up.

[#dist_design]
.Static map by blocks implemented
image::distribution_visualization.svg[align="center"]

NOTE: A simulation of job020, with 11 plates, in the Poas cluster, with 6 nodes available to act as workers and 1 as master, is used as an example to illustrate the distribution design implemented. Outlined arrows indicate communications between processes, where the end of the arrow points at the receiving process.

First of all, it was decided that the first process (with rank 0), would be the master, in charge of delegating plates to other processes for heat transfer simulation. Given that each process has their copy of the plates array (distribution begins until the simulation part), master and workers communicate by sending plates indexes and results: master first assigns one plate to each worker, then waits for results, capturing index and state to update in its own record. If it is still necessary to simulate plates, it assigns another plate index to the process it last received a result from, since it knows it will be free.

Once all plates have been updated and the last process has finished doing the last plate, the master process signals the other processes to end with the plates count. The master process finishes by reporting the results in a file.

In <<dist_design>> the current index is 6, so the first process to finish and send a result back, will be assigned the plate at index 6. This shall continue until plate at index 10 is finished by some process, at which point the stop signals will be sent to all processes.

Note that if there are more processes than plates to simulate, only plates amount of working processes will be needed. The rest will halt once the m