// Copyright 2025 Evan Chen Cheng <evan.chen@ucr.ac.cr>

#ifndef ERRORS_H
#define ERRORS_H

enum {
  ERR_NO_JOB_FILE = EXIT_FAILURE + 1,
  ERR_INVALID_THREAD_COUNT
};

// JOB RELATED
enum {
  JOB_INIT_FAIL = 11,
  JOB_FILE_NOT_FOUND,
  PLATE_ALLOCATION_FAIL,
  PLATE_FILE_NAME_ALLOCATION_FAIL,
  JOB_EXPANSION_FAIL,
  BUILD_RESULTS_FILE_PATH_FAIL,
  OPEN_RESULTS_FILE_FAIL
};

// PLATE_RELATED
enum {
  OPEN_PLATE_FILE_FAIL = 21,
  UPDATE_OUTPUT_FILE_NAME_FAIL,
  ROWS_COLS_READING_FAIL,
  BUILD_OUTPUT_FILE_NAME_FAIL,
  OPEN_OUTPUT_FILE_FAIL
};


#endif  // ERRORS_H
