// Copyright 2025 Evan Chen Cheng <evan.chen@ucr.ac.cr>

#ifndef ERRORS_H
#define ERRORS_H

#include <stdlib.h>

enum {
  ERR_NO_JOB_FILE = EXIT_FAILURE + 1,
  ERR_INVALID_THREAD_COUNT
};

// JOB RELATED
enum {
  ERR_JOB_INIT = 11,
  ERR_JOB_FILE_NOT_FOUND,
  ERR_PLATE_ALLOC,
  ERR_PLATE_FILE_NAME_ALLOC,
  ERR_JOB_EXPANSION,
  ERR_RESULTS_FILE_PATH,
  ERR_OPEN_RESULTS_FILE
};

// PLATE RELATED
enum {
  ERR_OPEN_PLATE_FILE = 21,
  ERR_UPDATE_OUTPUT_FILE_NAME,
  ERR_ROWS_COLS,
  ERR_BUILD_OUTPUT_FILE_NAME,
  ERR_OPEN_OUTPUT_FILE
};

// THREADS RELATED
enum {
  ERR_CREATE_THREAD_TEAM = 31,
  ERR_CREATE_THREAD
};
#endif  // ERRORS_H
