= Design of solution
:experimental:
:nofooter:
:source-highlighter: pygments
:stem:
:toc:
:xrefstyle: short

#Provide artifacts that help explain the design of your solution. For example, if your solution is multi-paradigm, you may provide a section for each one. The next sections are examples.#

[[object_design]]
== Object-oriented design

#Create UML artifacts using a design tool, e.g: diagrams.net. Export your diagrams to SVG format. Explain your designs in text, e.g: <<class_diagram>>.#

[#class_diagram]
.UML class diagram (click to open original)
image::class_diagram.svg[link="<url-provided-by-your-design-tool>"]



[[procedural_design]]
== Procedural design

=== main
The main procedure is in charge of processing the arguments received in the execution command, and notify any anomalies related to the input to the user. Then, it calls simulate() in simulation.c and later returns the error code returned by said procedure. The pseudocode for main() can be found below.

[#pseudocode]
[source,delphi]
----
include::main.pseudo[]
----

Note that the thread_count part will be implemented in the second part of this homework.

=== common
A section for common code was added to store string manipulation functions like build_file_path() (concatenates file name to directory), extract_directory(), extract_file_name(), and modify_extension() (returns modified extension of given file path). These were thought up to properly control where to find files to read or write in, for example to store simulated plates in the source directory, or writing .tsv reports of simulations. ChatGPT's assistance was needed for this part. Self-written pseudocode for each procedure:

[source,delphi]
----
include::common.pseudo[]
----

=== plate_matrix
The subroutines associated to the plate_matrix_t struct involve allocation and deallocation of memory for the matrices, the management of the auxiliary matrix (switching with main matrix before each temperature update), and the application of the formula for calculating a cell's new temperature (update_cell(), most notable subroutine of this section).

[source,delphi]
----
include::plate_matrix.pseudo[]
----
