= Design of solution
:experimental:
:nofooter:
:source-highlighter: highlightjs
:sectnums:
:stem: latexmath
:toc:
:xrefstyle: short

[[analysis]]
== Initial Analysis (Brainstorm)



[[data_structures]]
== Data structures
Two main data structures were used in this solution. For instance, job_t is a dynamic array that holds plate_t structs, which in turn contain a plate_matrix_t struct that holds two matrices of doubles: matrix and auxiliary_matrix. The former holds new temperatures while the latter holds current ones, switching before updating temperatures.

Below is an informal drawing of the described design.

[#data_structures_drawing]
.Data structures represented
image::data_structures.svg[align="center"]

[[object_design]]
== Object-oriented design

After the breakdown, the brainstormed subroutines were divided into different categories, some with structs (job_t, plate_t, and plate_matrix_t). The struct plate_matrix_t was thought up to better divide operations related with the process of simulating temperature changes and the actions before and after the simulation (which will be related to the plate_t struct). 

<<class_diagram>> shows the relationship in the division. Note that arrows point to files included, with a blank source rombus meaning aggregation, and filled in source rombuses meaning composition. For the effects of this diagram, files will be considered classes. Names ending in "_t" indicate structs, with attributes listed with "-", and related functions listed with "+". *common* is the only file without struct definition, not to mention the *main* file, which runs the simulate() procedure.

[#class_diagram]
.UML class diagram for the program
image::heat_simul_uml.svg[align="center"]



[source,delphi]
----
include::pseudocode/main.pseudo[]
----

Note that the thread_count part will be implemented in the second part of this homework.

