// Copyright 2025 Evan Chen Cheng <evan.chen@ucr.ac.cr>

#ifndef ERRORS_H
#define ERRORS_H

// JOB RELATED
#define JOB_INIT_FAIL 11
#define SET_PLATE_MATRIX_FAIL 12
#define UPDATE_PLATE_FILE_FAIL 13
#define JOB_FILE_NOT_FOUND 14
#define PLATE_ALLOCATION_FAIL 15
#define PLATE_FILE_NAME_ALLOCATION_FAIL 16
#define JOB_EXPANSION_FAIL 17
#define BUILD_RESULTS_FILE_PATH_FAIL 18
#define OPEN_RESULTS_FILE_FAIL 19

// PLATE_RELATED
#define OPEN_PLATE_FILE_FAIL 21
#define ROWS_COLS_READING_FAIL 22
#define OPEN_OUTPUT_FILE_FAIL 23

#endif  //ERRORS_H
