// Copyright 2025 Evan Chen Cheng <evan.chen@ucr.ac.cr>

#ifndef ERRORS_H
#define ERRORS_H

#define NO_JOB_FILE_SPECIFIED 10

// JOB RELATED
#define JOB_INIT_FAIL 11
#define JOB_FILE_NOT_FOUND 12
#define PLATE_ALLOCATION_FAIL 13
#define PLATE_FILE_NAME_ALLOCATION_FAIL 14
#define JOB_EXPANSION_FAIL 15
#define BUILD_RESULTS_FILE_PATH_FAIL 16
#define OPEN_RESULTS_FILE_FAIL 17

// PLATE_RELATED
#define OPEN_PLATE_FILE_FAIL 21
#define UPDATE_OUTPUT_FILE_NAME_FAIL 22
#define ROWS_COLS_READING_FAIL 23
#define BUILD_OUTPUT_FILE_NAME_FAIL 24
#define OPEN_OUTPUT_FILE_FAIL 25

#endif  // ERRORS_H
