// Copyright 2025 Evan Chen Cheng <evan.chen@ucr.ac.cr>

#ifndef ERRORS_H
#define ERRORS_H


enum {
  ERR_NO_JOB_FILE = EXIT_FAILURE + 1,
  // ERR_INVALID_THREAD_COUNT
};

// SIMULATION RELATED
enum {
  ERR_JOB_FILE_NOT_FOUND = 11,
  ERR_RESULTS_FILE_PATH,
  ERR_PLATE_FILE_SOURCE,
  ERR_OPEN_RESULTS_FILE,
  ERR_PLATE_ALLOC,
  
};

// PLATE RELATED
enum {
  ERR_PLATE_FILE_NAME_ALLOC = 21,
  ERR_PLATE_FILE_PATH_ALLOC,
  ERR_OPEN_PLATE_FILE,
  ERR_ROWS_COLS,
  ERR_UPDATE_OUTPUT_FILE_NAME,
  ERR_BUILD_OUTPUT_FILE_NAME,
  ERR_OPEN_OUTPUT_FILE
};

#endif  // ERRORS_H
